/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulario;

import java.util.HashSet;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author jez_3
 */
public class Principal extends javax.swing.JFrame {
    
    

    /**
     * Creates new form Principal
     */
    public Principal() {
        this.setTitle("Credenciales");
        this.setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTcorreo = new javax.swing.JTextField();
        jLIS1 = new javax.swing.JLabel();
        jLIS = new javax.swing.JLabel();
        jLfondoIS = new javax.swing.JLabel();
        jLIS2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTpass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel3.setText("inicio de secion");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setToolTipText("");
        jPanel1.setMaximumSize(new java.awt.Dimension(450, 360));
        jPanel1.setName("Credenciales"); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTcorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTcorreoActionPerformed(evt);
            }
        });
        jPanel1.add(jTcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 230, 30));

        jLIS1.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLIS1.setForeground(new java.awt.Color(51, 51, 51));
        jLIS1.setText("Contraseña:");
        jLIS1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLIS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 110, -1));

        jLIS.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLIS.setText("Inicio de Sesion");
        jLIS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLIS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 140, -1));

        jLfondoIS.setBackground(new java.awt.Color(255, 255, 255));
        jLfondoIS.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLfondoIS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo1.jpg"))); // NOI18N
        jLfondoIS.setText("inicio de secion");
        jPanel1.add(jLfondoIS, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 160, 40));

        jLIS2.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLIS2.setForeground(new java.awt.Color(51, 51, 51));
        jLIS2.setText("Correo:");
        jLIS2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLIS2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 70, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/candado.png"))); // NOI18N
        jButton1.setText("Verificar");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 150, 40));
        jPanel1.add(jTpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 230, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo1.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 390, 240));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int contraseña;
        String correo;
        //Evaluo
        
        if(jTcorreo.getText().isEmpty() || jTpass.getText().isEmpty()){
        
            JOptionPane.showMessageDialog(this, "Hay campos sin completar");
            return;
        }
        
        contraseña=123456789;
        correo="alumno@ulp.com.ar";
      
        boolean bandera=false;
        
        
            if(jTcorreo.getText().equals(correo)||jTpass.getText().equals(contraseña)){
                bandera=true;
                //JOptionPane.showMessageDialog(this,"credenciales correctas");
                Acceso a=new Acceso();
                a.setVisible(bandera);
                dispose();
              }
            if(!bandera){
        
            JOptionPane.showMessageDialog(this,"Usuario y/o contraseña incorrectos");
            limpiarCampos();
    }                
    }//GEN-LAST:event_jButton1ActionPerformed

    public void limpiarCampos(){
        jTcorreo.setText("");
        jTpass.setText("");
    }
    
    
    
    private void jTcorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTcorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTcorreoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLIS;
    private javax.swing.JLabel jLIS1;
    private javax.swing.JLabel jLIS2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLfondoIS;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTcorreo;
    private javax.swing.JPasswordField jTpass;
    // End of variables declaration//GEN-END:variables
}
